### ISSUE TITLE
Assignment 1- Ready for Grading

### ISSUE THREAD

**Issue by sage-grey-voorhees** [SES-5215-F2020/svoorhees-quant#1]
Thanks, Teaching Team! I'm relatively new to GitHub, R, and coding generally. The video and written tutorials were very very helpful. As were the huge bounty of OH appointments. Thank you for the effort that was put into those!

**Comment by sage-grey-voorhees** [comment]
I didn't know to assign @c-voulgaris originally, but here is my first assignment for quant

**Comment by saratepfer** [comment]
Thank you, Sage! Nice work here! Your unit of analysis and who's included in your population are both clearly stated. It's important to also state the number of observations in your dataset. 

**Comments on Content**
I believe you are using the flag variable FHINCP instead of the HINCP variable, which actually reports the numeric values of income. Was this intentional?

**Comments on Code**
Lines 80-90: It looks like your definition for structures built in the last 20 years does not go back 20 years. Is there a reason you didn't include 2000-2007?

I would check in with Carole about the issue you note in #2 of next steps. I'm not sure what is going on there.
