### ISSUE TITLE
Assignment 2: Ready for Grading

### ISSUE THREAD

**Issue by sage-grey-voorhees** [SES-5215-F2020/svoorhees-quant#2]
Thank you so much for your help this week! Really feel like I'm getting comfortable with R!

**Comment by saratepfer** [comment]
nice job, Sage! A few comments, below:

- lines 62, 115, 159, 202: Is the dollar sign at the end of these lines of code intentional?
- When you set up your ggplots, you can specify the number of bins. R/GGPlot default to 30 bins. In your case, for your first histogram, I would reduce the number of bins to remove the gaps you see in your histogram. (you can also increase the binwidth; either way!)
- You can use the prettynum() function in your proportion tables for your categorical variables to reduce the number of digits after the decimal place. For example, "prettynum(fourties$estimate, digit = 3)" will reduce the number of digits for the proportion estimate for the 1940s category.
- You can angle the x-axis labels on your plot to make room for the long category names. You can do so by doing all of your plot code + theme(axis.text.x = element_text(angle = 45). Alternatively, you could do a coord_flip()
